steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/searce-01/helloworld:latest', '.']
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/searce-01/helloworld:latest']
 
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'helloworld', '--image', 'gcr.io/searce-01/helloworld', '--port', '80', '--region', 'europe-west1', '--platform', 'managed', '--allow-unauthenticated']
images:
 - 'gcr.io/searce-01/helloworld:latest'

